### ISSUE TITLE
Make extensions more browser-friendly

### ISSUE THREAD

**Issue by dkichler** [kuitos/axios-extensions#10]
This is a simple, useful extension that I would love to use.  However, it is not very browser friendly for these reasons:
- has an unnecessarily large footprint with the dependency on Lodash for the use of a simple `isEmpty` method, which only needs to validate simple `object` types. 
- Dependency on node modules `url` and `querystring` for other similarly simple tasks.

I propose that all of the above functions be replaced with lightweight, browser friendly alternatives.

**Comment by lhermann** [comment]
@dkichler I second this request. It's a great extension but it added 200 kb to my js build. I saw that you forked the this repo, are you going to create a pull request?

**Comment by dkichler** [comment]
I'm exploring options at the moment, but yes, I had intentions of posting a PR here once I've settled on something sufficient.  After opening this ticket, I noticed the authors comments to [this similar ticket](https://github.com/kuitos/axios-extensions/issues/3#issuecomment-357671339)  and decided to do a more thorough analysis of the final build size.  Your comments suggest you have at least a rough idea (200kb), which I think still presents opportunity for trimming.

**Comment by kuitos** [comment]
thanks for your feedback!😀
here is the bundle analysis(from `webpack-bundle-analyzer`):
![image](https://user-images.githubusercontent.com/5206843/37381798-28fca342-277a-11e8-8d04-3cd2537d52f8.png)
bundle: 183kb  uglify+gzip: 22.21kb

The largest part of the bundle was dependencies on node_modules which could be replaced by lightweight alternatives or implemented with ourself.
@dkichler @lhermann feel free to submit a PR for fixing this.😄

**Comment by lhermann** [comment]
Indeed, with uglify the size becomes much smaller. However, there is still virtue in getting rid of dependencies I believe.

I am waiting what @dkichler comes up with :)

**Comment by kuitos** [comment]
After https://github.com/kuitos/axios-extensions/issues/9 fixed, the `lodash` `querystring` and `url` modules were removed from the library. And the bundle was reduced to half its previous size nearly.

**Comment by kuitos** [comment]
now the largest module is core-js which comes with babel transforming.
And then the second largest part is `lru-cache` module and those it referenced.
![image](https://user-images.githubusercontent.com/5206843/37391104-307609a8-27a5-11e8-8e05-78f715833dd9.png)

**Comment by dkichler** [comment]
Depending on `buildURL` from axios was the same solution I came to and addresses this and #9!  Nice fix  @kuitos and thanks for the prompt release.
