### ISSUE TITLE
Axios should be a `peerDependency` 

### ISSUE THREAD

**Issue by jmendiara** [kuitos/axios-extensions#13]
Having as a dependency leads to have duplicated dependencies and may lead to inconsistencies

```sh
$ npm ls axios

myproject@0.0.0
├── axios@0.18.0
└─┬ axios-extensions@2.0.0
  └── axios@0.16.2
```

**Comment by kuitos** [comment]
resolved, see https://github.com/kuitos/axios-extensions/issues/14
