### ISSUE TITLE
`babel-runtime` should be in `devDependencies`

### ISSUE THREAD

**Issue by probil** [kuitos/axios-extensions#15]

**Comment by kuitos** [comment]
When the `transform-runtime` plugin enabled, the compilation will refer the `babel-runtime` library, so it should be in `dependencies` that we will certainly have the whole dependencies while installing `axios-extensions` ensure

**Comment by probil** [comment]
Hmm... Ok, I see. I thought you provide precompiled version of the library

**Comment by kuitos** [comment]
All the provided versions are compiled 😄
