### ISSUE TITLE
Persistent cache

### ISSUE THREAD

**Issue by SirWindfield** [kuitos/axios-extensions#19]
Is it currently possible to use this library as a persistent cache ? Meaning that, after restarting the application, the cache can be loaded into memory and directly reused ? 
I would need something like this in my current node project .

**Comment by kuitos** [comment]
U can construct a cache-like instance which define a custom set method to persistent your data, see https://github.com/kuitos/axios-extensions#more-advanced

**Comment by SirWindfield** [comment]
Thanks! I actually didn't notice it, sorry for the inconvenience :smile:

**Comment by kuitos** [comment]
you're welcome! feel free to ask any questions about the library usage!🙂
