### ISSUE TITLE
Add `repository` and `license` field to package.json

### ISSUE THREAD

**Issue by probil** [kuitos/axios-extensions#20]
Repository field is pretty useful, it allows to open github page right from npm page.
Also it helpful for people who wants to contribute.  
```
npm WARN axios-extensions@2.0.3 No repository field.
npm WARN axios-extensions@2.0.3 No license field.
```
https://docs.npmjs.com/files/package.json#repository

**Comment by kuitos** [comment]
added and v3.0.0 released
