### ISSUE TITLE
Different TTL's for individual requests?

### ISSUE THREAD

**Issue by eldub2001** [kuitos/axios-extensions#25]
Is there a way to set different ttl's for individual requests? 

Seems like setting one maxAge for all items in the cache isn't ideal. 
It would be nice if there was a way to do something like the following:
1. Set when making the request ( I know I want this to only persist for X time so do that )
2. Use Cache-control header max-age value - age (The server knows best, so respect that)
3. Use default maxAge, (I didn't set anything and the server told me nothing so cache for default time)

Thoughts?

**Comment by kuitos** [comment]
U can give the request an individual cache when it making:
```js
const cacheA = new Cache({maxAge: 100 * 1000});
const cacheB = new Cache({maxAge: 100 * 1000});
http.get('/users', { cache: cacheA });
http.get('/users', { cache: cacheB });
```
see https://github.com/kuitos/axios-extensions#more-advanced
