### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by loic-lopez** [kuitos/axios-extensions#26]
Hi, 

I would like to know if `cacheAdapterEnhancer` will work in react-native.

Thanks for reply.

**Comment by kuitos** [comment]
All implementation are based on standard JavaScript and axios, theoretically it will.

**Comment by loic-lopez** [comment]
Thanks for reply!

Do you know how i can test the cache?

**Comment by kuitos** [comment]
If you need verify in unit test, check this https://github.com/kuitos/axios-extensions/blob/master/src/__tests__/test-cacheAdapterEnhancer.ts

Or you can check the network monitor, an cached request should not make a real network invocation.

Feel free to ask any questions😀.

**Comment by loic-lopez** [comment]
Thanks for reply!

**Comment by kuitos** [comment]
you're welcome
