### ISSUE TITLE
Cache actual data, not a promise

### ISSUE THREAD

**Issue by eugene-daragan-codex** [kuitos/axios-extensions#29]
Using response promises as cache items makes impossible to use options like `max` in node-lru-cache library because size of cached item is evaluated in cache's `set` method, when the promise is not resolved.

**Comment by kuitos** [comment]
Very valuable issue!👍
We could treat the promise as a placeholder of actual response in cache, and we set the promise to cache no matter it had been resolved or not(delete when it be rejected), the `max` feature of lru cache would not be lost.
