### ISSUE TITLE
reduce the production size

### ISSUE THREAD

**Issue by Hongbo-Miao** [kuitos/axios-extensions#3]
I saw the package only uses `isEmpty` from lodash.
So maybe just install `lodash.isempty` instead of `lodash`?

Or use own function something like
```js
function isEmpty(obj) {
  if (!obj) return true;
  return !Object.keys(obj).length;
}
```

It will help reduce the production size.

The package is awesome! Very easy to use. Thank you!

**Comment by kuitos** [comment]
Thanks for your advice and nice comment!😄
https://github.com/kuitos/axios-extensions/blob/ecf6a36efb47e3655533dd2c57f1b9b68eeb8ec8/.babelrc#L9
I used the babel-plugin-lodash to cherry-pick the lodash modules in compile time, thus the bundle size will be optimized automatically. see the published npm package which after babel tranform.https://unpkg.com/axios-extensions@1.1.3/esm/utils/buildUrl.js

**Comment by Hongbo-Miao** [comment]
Got it, thanks!
