### ISSUE TITLE
[Feature] a flag to cache failed responses

### ISSUE THREAD

**Issue by hobochild** [kuitos/axios-extensions#30]
I'd like to not delete the cache key on failed requests. Would it make sense for an extra option cache failed responses too?

**Comment by kuitos** [comment]
Cache a failed response? any scenario had you met?

**Comment by hobochild** [comment]
Nevermind :)  I was seeing duplicate failed requests, but it turned out all the failed requests wherein flight when they hit the cache, so there actually weren't any duplicates - as they all pointed to the same promise. But the axios logger made it look as if there were duplicates. 

So no need for this in my usecase actually :+1:

**Comment by kuitos** [comment]
Thanks for your feedback！
