### ISSUE TITLE
TypeScript: module '...lru-cache' has no default export

### ISSUE THREAD

**Issue by tmladek** [kuitos/axios-extensions#31]
Hello, as of today, with the latest version of both axios extensions and lru-cache, I get the following error while compiling with typescript:

```
ERROR in /.../node_modules/axios-extensions/lib/index.d.ts(6,8):
TS1192: Module '"/.../node_modules/@types/lru-cache/index"' has no default export.
Version: typescript 2.9.2
```

And it indeed is true; I had to change line 

`import Cache from 'lru-cache';`
to
`import {Cache} from 'lru-cache';`

And it compiles succesfully.

**Comment by kuitos** [comment]
have you ever enable the ts config `esModuleInterop: true` ?

**Comment by tmladek** [comment]
I did now, and the error still remains.

**Comment by tmladek** [comment]
When I try to `import Cache from 'lru-cache'`, enabling `esModuleInterop` works; however, when I am not importing it directly, and only, for example `import {cacheAdapterEnhancer} from 'axios-extensions'`, it doesn't matter what `esModuleInterop` is set to, I get the error.

**Comment by tmladek** [comment]
Minimal example here: https://gist.github.com/tmladek/2b25461159d60fe4568de85b071b73a3

**Comment by tmladek** [comment]
Yes, `"allowSyntheticDefaultImports": true` does fix the issue. Thank you!

**Comment by kuitos** [comment]
Thanks for your feedback!
