### ISSUE TITLE
Question: how do you log along with Vue-Cli?

### ISSUE THREAD

**Issue by super2ni** [kuitos/axios-extensions#35]
Hello there,

First of all thank you for your magnificient work.

I'm starting to work on a Vue SPA for the first time using **Vue-Cli**. I used your projet to have throttling and caching on my Ajax requests. It seems to work well but I would like to have logs on the console so my developpers can know what is happening.

I know I'm supposed to add this to my webpack.config:
`new webpack.DefinePlugin({
  'process.env.LOGGER_LEVEL': JSON.stringify('info')
})`

So on my ".env" file I tried to put this:
`LOGGER_LEVEL='info'`
or even this
`LOGGER_LEVEL=info`

But no luck...

Do you mind to help me?

Thank you,
Denis

**Comment by kuitos** [comment]
You can create a `vue.config.js` file to merge your custom webpack configuration.
```js
// vue.config.js
const webpack = require("webpack");

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.DefinePlugin({
        "process.env.LOGGER_LEVEL": JSON.stringify("info")
      })
    ]
  }
};
```
check the doc https://cli.vuejs.org/guide/webpack.html#simple-configuration and the relate issue https://github.com/vuejs/vue-cli/issues/787

**Comment by super2ni** [comment]
You are awesome!

Tyvm
