### ISSUE TITLE
cacheFlag not working in react native

### ISSUE THREAD

**Issue by techgig17** [kuitos/axios-extensions#36]
When I use CacheFlag to control caching, CacheFlag is not working in react native as expected. config[cacheFlag] is always undefined in  cacheAdapterEnhancer.js. Hence it is not caching

My code is as below

const axiosClient = axios.create({
    baseURL: HOST,
    headers: {
        'Content-type': 'application/json',
        'Cache-Control': 'no-cache'
    },
	adapter: cacheAdapterEnhancer(axios.defaults.adapter, { enabledByDefault: false, cacheFlag: 'useCache'})
});

then in a function
return await axiosClient.get(URL, params, {useCache : true});

If i change in cacheAdapterEnhancer.js

var useCache = (config[cacheFlag] !== void 0 && config[cacheFlag] !== null) ? config[cacheFlag] : enabledByDefault;

to

var useCache = (cacheFlag !== void 0 && cacheFlag !== null) ? cacheFlag : enabledByDefault;

Now the flag works as expected. Kindly help with the issue

**Comment by kuitos** [comment]
sorry for the delay, I saw u had closed the issue, the problem had been solved?
