### ISSUE TITLE
Cache a timeout request

### ISSUE THREAD

**Issue by hardware** [kuitos/axios-extensions#37]
Hi,

Is it possible to cache a request, even when the `validateStatus` return `false` or when you got a timeout ? I need to save this state to not have thousands of timed out requests in my heroku backlog. I use your extension to handle a status website for a AAA game.

Thanks.

**Comment by kuitos** [comment]
> Is it possible to cache a request, even when the validateStatus return false or when you got a timeout ?

Sorry it may can't. We shouldn't cache an error request in general, u may need to write a special adapter to handle it. such as: 

```js
import axios from 'axios';

async function timeoutAdapter(adapter) {
  try {
    return await adapter(config);
  } catch(e) {
    if(e. statusText === 'timeout') {
        return 'xxx'
    }

    throw e;
  }
}

const http = axios.create({
	baseURL: '/',
	headers: { 'Cache-Control': 'no-cache' },
	adapter: cacheAdapterEnhancer(timeoutAdapter(axios.defaults.adapter))
});

```

**Comment by hardware** [comment]
Ok, I understand, thank you for this advice. I think I will handle that myself.

**Comment by kuitos** [comment]
Great! Thanks for your feedback!
