### ISSUE TITLE
Implement CHANGELOG.md for future releases

### ISSUE THREAD

**Issue by crobinson42** [kuitos/axios-extensions#38]
Hi, great library!

I wanted to suggest/request the use of a CHANGELOG.md file at the root of the repo that outlines changes (breaking, features, fixes, etc.) between releases 👍

**Comment by kuitos** [comment]
Thanks for your cool advice:+1:
This library looks relatively stable now, if the next version makes a breaking changes or a feature I will add a changlog.
Thanks for your nice feedback:smile:

**Comment by kuitos** [comment]
now the release page has the changelog https://github.com/kuitos/axios-extensions/releases
