### ISSUE TITLE
Use pending GET request

### ISSUE THREAD

**Issue by crobinson42** [kuitos/axios-extensions#39]
An idea for an enhancement to throttle or cache adapters as a flag `usePendingRequest`.

If there is a pending [similar] request, then the call returns a promise which will resolve the same as the current request.

An example of this need can be in a framework like React or Angular where a UserName component is mounted in 2 separate DOM locations and they both make the request to fetch user data. If they both mount within milliseconds, neither will see a cached request and start a new request. This feature would reduce simultaneous "like" requests in this situation by returning a promise for the first request made.

I'm happy to contribute this effort, please advise :-)

**Comment by kuitos** [comment]
Sorry for the delay, in vacation the past days😬
I think this feature had already been implemented by `cachedAdapterEnhancer` as js was a 'single thread' programming language, for example:
```js
// had enabled cacheAdapterEnhancer
http.get('users')
http.get('users') // the second one will use the previous respond promise
```
If I misunderstood your question, make me know🙂

**Comment by crobinson42** [comment]
@kuitos After testing this functionality from `cachedAdapterEnhancer`.

I did notice the passing of `cache`: false isn't actually bypassing the cache, see here:

https://runkit.com/crobinson42/axios-extensions-issues-39

**Comment by kuitos** [comment]
@crobinson42 You should not combine the `throttleAdapterEnhancer` with `cachedAdapterEnhancer ` while you wanna manual control the cache of request, just use `cachedAdapterEnhancer`:
```js
adapter: cacheAdapterEnhancer(axios.defaults.adapter)
```

**Comment by crobinson42** [comment]
That was taken from the example on the README.md of this repository.

**Comment by kuitos** [comment]
check the `cacheAdapterEnhancer` part😀 https://github.com/kuitos/axios-extensions#basic-usage
