### ISSUE TITLE
Got 405 error when try to get gravatars

### ISSUE THREAD

**Issue by Hongbo-Miao** [kuitos/axios-extensions#4]
axios-extensions works great for all my requests except for one: get gravatars.

If I use axios only, it works well.
```js
axios.get(
    'https://www.gravatar.com/avatar/46b999a5b1498f5ef58f767845942269?d=404', {
      responseType: 'arraybuffer'
    })
  .then(res => {
    // res.data is correct array buffer
  })
  .catch(err => {});

```

But if I change to
```js
const http = axios.create({
  baseURL: '/',
  headers: {
    'Cache-Control': 'no-cache'
  },
  adapter: cacheAdapterEnhancer(axios.defaults.adapter, true)
});

http.get(
    'https://www.gravatar.com/avatar/46b999a5b1498f5ef58f767845942269?d=404', {
      responseType: 'arraybuffer'
    })
  .then(res => {})
  .catch(err => {});
```
It will throw the error:

![image](https://user-images.githubusercontent.com/3375461/34940430-5dfed438-f9a4-11e7-9ce8-dec52764a637.png)

Any idea? Thanks

**Comment by kuitos** [comment]
u need to remove the cache-control header setting in your example.

**Comment by Hongbo-Miao** [comment]
Hi @kuitos thanks for help! It works perfect now. Would you mind explaining it a little bit for this case? Thanks

**Comment by kuitos** [comment]
It was a CORS issue, u can read this article for a complete understanding https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by Hongbo-Miao** [comment]
Thanks!
