### ISSUE TITLE
Failed call disappears from the cache

### ISSUE THREAD

**Issue by speyou** [kuitos/axios-extensions#41]
Hi, first I want to say this is an awesome lib! Thanks for sharing.
I'm not sure I am using it well in the following scenario:
1- cache all requests
2- forceUpdate all requests in order to have the latest data from server
3- if a request fails because of lost connection, I start a so called "offline mode" and set forceUpdate to false
4- I can use my app offline if I go on all the places I already went to (because they are cached)
5- all the places BUT the first one, the one that failed at step 3. It's either not cached or cached with failure. Even if I had it cached previously, I lost the data.

My question is: is it possible to keep the cache even if the axios call is rejected?

**Comment by kuitos** [comment]
Sorry for the delay, and thanks for your nice comment!
Your question may related with this issue https://github.com/kuitos/axios-extensions/issues/37
Feel free to ask any questions!

**Comment by speyou** [comment]
No problem for the delay, thanks very much for your answer!
I tried to play with a customAdapter on top of yours but I don't find a way to:
a) prevent the deletion of the cached result
b) make another call to the cache

```
function customAdapter(adapter) {
  return async config => {
    try {
      // I think cache.del(index) will be called here anyway
      return await adapter(config);
    } catch (e) {
      if (e.request && e.request.status === 0) {
        // how to call cacheAdapterEnhancer again and cache.get(index)?
      }
      throw e;
    }
  };
}

export const http = axios.create({
  // setup default URL
  baseURL: API_URL,
  headers: { "Cache-Control": "no-cache" },
  adapter: cacheAdapterEnhancer(customAdapter(axios.defaults.adapter))
});
```

**Comment by kuitos** [comment]
You can make a request interceptor which return the previous cache while in 'offline mode'.
here is minimal example you can refer to:
```js



import { Cache, cacheAdapterEnhancer } from 'axios-extensions'
import buildSortedURL from 'axios-extensions/lib/utils/buildSortedURL'

const cache = new Cache();

export const http = axios.create({
  // setup default URL
  baseURL: API_URL,
  headers: { "Cache-Control": "no-cache" },
  adapter: cacheAdapterEnhancer(axios.defaults.adapter, { defaultCache: cache }))
});

http.interceptors.request.use(config => config, error => {
  if (inOfflineMode) {
    const { url, params, paramsSerializer } = errror.config
    const index = buildSortedURL(url, params, paramsSerializer)
    return cache.get(index)
  }

  return Promise.reject(error)
})
```

**Comment by kuitos** [comment]
Awesome workaround!
From my rough review, my advice is that u could use the native web api to check the offline status, such as [navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events), and remove the offlineResponseErrorInterceptor interceptor.

```js
export function offlineRequestInterceptor(config) {
  // since cache is enabled by default
  // we need to specify forceUpdate
  // in order to always get the latest data from server
  config.forceUpdate = true;

  // in case of offline, we stop updating
  // and return the cached result instead
  if (navigator.onLine === false) {
    config.forceUpdate = false;
    const index = buildSortedURL(url, params, paramsSerializer);
    offlineCache.set(index, cache.get(index));
  } 
  return config;
}

export async function offlineResponseErrorInterceptor(error) {
  // error.request is an instance of XMLHttpRequest
  const status = error.request && error.request.status;

  if (navigator.onLine === false) {
    const { method, url, params, paramsSerializer } = error.config;
    // get the cached version (if any)
    if (method === "get") {
      const index = buildSortedURL(url, params, paramsSerializer);
      // the beauty of it reside in the fact that
      // requests won't fail if cached by regular cache
      // so offline cache will get useful only for the first few timeout-pending requests
      return offlineCache.get(index);
    }
  }

  // if error is not handled yet, we return falty promise
  return Promise.reject(error);
}


```

**Comment by kuitos** [comment]
And, if you do not wanna enable the cache by default, no need to set forceUpdate to true, you could set the config like this:

```js
adapter: cacheAdapterEnhancer(axios.defaults.adapter, { enabledByDefault: false }))
```

For more information u could check the api doc https://github.com/kuitos/axios-extensions#cacheadapterenhancer

**Comment by speyou** [comment]
If I don't enabledByDefault I witnessed it won't cache anything. I want it to cache but I don't want it to access this cache unless its offline.

Anyway you answered my doubts and I have a neat feature thanks to you now, we can close. :)
