### ISSUE TITLE
IE error

### ISSUE THREAD

**Issue by sunilsharma2214** [kuitos/axios-extensions#42]
**getting Syntax error**
Syntax error
bundle.js (1377,24)

const naiveLength = () => 1

Working fine in chrome and Edge.

**Comment by sunilsharma2214** [comment]
code is working fine in Chrome and edge but getting error on IE for below code 
bundle.js (1377,22)
error at  const naiveLength = () => 1 

**index.tsx**
import 'core-js/shim';

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import '@awms/frontend-components/es/styles.deprecated/css/index.css';
import TestComponent from 'components/TestComponent';

export const rootReactElement = (
  <div>
    Hello world
    <TestComponent title="CST tool" />
  </div>
);

const rootHTMLElement = document.getElementById('root');

if (rootHTMLElement) {
  ReactDOM.render(rootReactElement, rootHTMLElement);
}
-------------------------
**TestComponent.tsx**
/* Default Cache Maxage */
const defaultCache = new Cache({ maxAge: 100 * 1000 });

/* Axios instance with cache enhancer */
const Axios = axios.create({
    baseURL: 'https://jsonplaceholder.typicode.com/',
    //@ts-ignore
    adapter: cacheAdapterEnhancer(axios.defaults.adapter, 'cache', defaultCache)
}); 

const TestComponent: React.SFC<Props> = props => {
  return <div>{ Axios.get('users/1')}</div>
};

export default TestComponent;
----------------------------------------
**package.json**
{
  "name": "client-segmentation",
  "version": "0.0.1",
  "private": true,
  "homepage": ".",
  "dependencies": {
    "@types/classnames": "2.2.3",
    "@types/enzyme": "3.1.10",
    "@types/enzyme-adapter-react-16": "1.0.2",
    "@types/jest": "22.2.3",
    "@types/lodash": "4.14.109",
    "@types/node": "10.1.0",
    "@types/react": "16.3.14",
    "@types/react-dom": "16.0.5",
    "@types/react-redux": "6.0.0",
    "axios": "^0.18.0",
    "axios-cache-adapter": "^2.1.1",
    "axios-extensions": "^3.0.4",
    "classnames": "2.2.5",
    "core-js": "2.5.7",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "1.1.1",
    "lodash": "4.17.10",
    "moment": "2.22.1",
    "react": "16.3.2",
    "react-datepicker": "1.5.0",
    "react-dom": "16.3.2",
    "react-redux": "5.0.7",
    "redux": "3.7.2",
    "redux-devtools-extension": "2.13.2",
    "redux-thunk": "2.2.0",
    "tslint": "5.9.1",
    "typescript": "3.0.1"
  },
  "description": "",
  "scripts": {
    "build": "react-scripts-ts build",
    "eject": "react-scripts-ts eject",
    "start": "react-scripts-ts start",
    "test": "npm run tslint && npm run test:unit:coverage",
    "test:unit:coverage": "react-scripts-ts test --env=jsdom --coverage",
    "test:unit:watch": "react-scripts-ts test --env=jsdom --watch",
    "tslint": "tslint --project .",
    "tslint:fix": "npm run tslint -- --fix",
    "cy:open": "cypress open",
    "cy:run": "cypress run"
  },
  "jest": {
    "collectCoverageFrom": [
      "**/*.{ts,tsx}",
      "!**/*.{d}.*",
      "!**/node_modules/**"
    ]
  },
  "devDependencies": {
    "cypress": "^3.1.3"
  }
}
------------------------
**tsconfig.json**
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es6",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "baseUrl": "./src",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
  },
  "exclude": [
    "node_modules",
    "es",
    "lib",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}

**Comment by kuitos** [comment]
search the statement `const naiveLength ` in your code base, axios-extensions hadn't such code.

**Comment by kuitos** [comment]
Well, this issue was the same as https://github.com/kuitos/axios-extensions/issues/40.
To solve this u need add the lru-cache library for babel compiler.

**Comment by kuitos** [comment]
@sunilsharma2214 released v3.0.5
Thanks for your feedback!

**Comment by sunilsharma2214** [comment]
this is what I found.... 

/***/ "./node_modules/axios-extensions/node_modules/lru-cache/index.js":
/*!***********************************************************************!*\
  !*** ./node_modules/axios-extensions/node_modules/lru-cache/index.js ***!
  \***********************************************************************/
/*! dynamic exports provided */
/*! exports used: default */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


// A linked list to keep track of recently-used-ness
const Yallist = __webpack_require__(/*! yallist */ "./node_modules/axios-extensions/node_modules/yallist/yallist.js")

const MAX = Symbol('max')
const LENGTH = Symbol('length')
const LENGTH_CALCULATOR = Symbol('lengthCalculator')
const ALLOW_STALE = Symbol('allowStale')
const MAX_AGE = Symbol('maxAge')
const DISPOSE = Symbol('dispose')
const NO_DISPOSE_ON_SET = Symbol('noDisposeOnSet')
const LRU_LIST = Symbol('lruList')
const CACHE = Symbol('cache')
const UPDATE_AGE_ON_GET = Symbol('updateAgeOnGet')

**const naiveLength = () => 1**

**Comment by kuitos** [comment]
Is the issue exist in v3.0.5 yet?

**Comment by sunilsharma2214** [comment]
@kuitos, Sorry I've not checked your previous comments.... , Yup this is fixed in V3.0.5. Thank You.

**Comment by kivervinicius** [comment]
./node_modules/axios-extensions/esm/index.js
Module not found:

In v3.0.5

**Comment by kuitos** [comment]
@kivervinicius 
I had checked the published version, https://unpkg.com/axios-extensions@3.0.5/esm/index.js is exist, could you provide the detail error stack?
