### ISSUE TITLE
[question] How to Check if the response is coming from the cache ?

### ISSUE THREAD

**Issue by felixdenoix** [kuitos/axios-extensions#43]

**Comment by kuitos** [comment]
@felixdenoix any details?

**Comment by felixdenoix** [comment]
First of all sorry for the empty question !
Secondly the question: 
Is there a way of checking the origin of the response ( cache/request ) when using the cacheAdapterEnhancer ?

**Comment by kuitos** [comment]
@felixdenoix why do you need the checking? could u pls provide the background?

**Comment by felixdenoix** [comment]
I'm using your module in a Nuxt (a Vue SSR wrapper) application with axios. At the moment i'm trying to cache the result of the requests server-side (and it seems that it is working) and to ensure that the cache transmitted to the client is containing the result of these requests.

Maybe that my understanding of the ssr framework is wrong but it seems that what I've done for the moment is working and I wanted to be sure that the cache stores the object contents

```javascript
import { cacheAdapterEnhancer } from "axios-extensions"
import LRUCache from "lru-cache"
const ONE_HOUR = 1000 * 60 * 60
const ONE_DAY = 24 * ONE_HOUR

const defaultCache = new LRUCache({ maxAge: ONE_DAY, max: 200 })

export default function ({ $axios, redirect, store }) {
	const defaults = $axios.defaults

	defaults.adapter = cacheAdapterEnhancer(defaults.adapter, {
		enabledByDefault: false,
		cacheFlag: "useCache",
		defaultCache
	})
}
```

Above is the nuxt plugin configuration file in my application if it can be of any help
