### ISSUE TITLE
CORS error when accessed from localhost

### ISSUE THREAD

**Issue by niksmac** [kuitos/axios-extensions#45]
I am getting `Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.` even though I have `access-control-allow-origin *` present in the response. 

It is working fine without axios-extensions

**Comment by kuitos** [comment]
more information need, such as your context code

**Comment by kuitos** [comment]
closed as inactived

**Comment by niksmac** [comment]
Apologies, but I have to gave up on using `axios-extensions` to get this working.
