### ISSUE TITLE
forcing `esModuleInterop` and `allowSyntheticDefaultImports` is too restrictive

### ISSUE THREAD

**Issue by chaoyangnz** [kuitos/axios-extensions#47]
I am working on a big project, we didn't and don't plan to enable `esModuleInterop`.

So that makes us unable to integrate this good library. As a library, assuming the consumer's setting seems not a good idea.

**Comment by kuitos** [comment]
why not enable these compatible feature

**Comment by chaoyangnz** [comment]
this is a good question. I tend to but this is not decided by me. Personally, I don't like synthetic things
