### ISSUE TITLE
HELP: No Logs is shown. Cant verify if request are actually cached

### ISSUE THREAD

**Issue by paolog22** [kuitos/axios-extensions#48]
here is my configuration on axios
![image](https://user-images.githubusercontent.com/12680745/55059098-0c71f200-50a9-11e9-8cef-5bd0f8d85d76.png)
How can i verify that request are being cache ? 

i am using vue with vue-cli 3

thanks in advance

**Comment by kuitos** [comment]
your configuration are missing..

**Comment by kuitos** [comment]
check the doc https://github.com/kuitos/axios-extensions#enable-logging

**Comment by paolog22** [comment]
already apply whats on the docs with webpack but cant see anything .. i see nothing in console

thanks

**Comment by kuitos** [comment]
paste your webpack configuration

**Comment by paolog22** [comment]
![image](https://user-images.githubusercontent.com/12680745/55877593-01e94980-5bcd-11e9-84d4-69e2155d6b0e.png)
here is my webpack config i am using vue-cli 3

**Comment by paolog22** [comment]
![image](https://user-images.githubusercontent.com/12680745/55877671-3d841380-5bcd-11e9-8034-08cb553df752.png)
here is my webpack config. i am using vue-cli 3

**Comment by kuitos** [comment]
can u make a reproduction with [codesandbox](https://codesandbox.io/)?

**Comment by kuitos** [comment]
The log appears only if more than two requests are sent @paolog22

**Comment by paolog22** [comment]
@kuitos got it.. thank you . i will now close this :)
