### ISSUE TITLE
Getting error while using useCache flag

### ISSUE THREAD

**Issue by sunilsharma2214** [kuitos/axios-extensions#58]
axios.ts file
const axiosAppInstance = axios.create({
  // @ts-ignore
  adapter: cacheAdapterEnhancer(axios.defaults.adapter, { enabledByDefault: false, cacheFlag: 'useCache'}),
  baseURL: appConfig.getRequired('abc'),
});

abc.ts file
 axiosAppInstance.get('xyz',{ useCache: true }),  

TypeScript error
Argument of type '{ useCache: boolean; }' is not assignable to parameter of type 'AxiosRequestConfig'.
  Object literal may only specify known properties, and 'useCache' does not exist in type 'AxiosRequestConfig'.ts

**Comment by kuitos** [comment]
here is the solution https://github.com/kuitos/axios-extensions#custom-cache-typing

**Comment by adbutterfield** [comment]
I try not to comment on closed issues but...
I'm getting:

> node_modules/axios-extensions/esm"' has no exported member 'ICacheLike'

using the solution above.

**Comment by adbutterfield** [comment]
Oh, I guess the change not released yet.

**Comment by kuitos** [comment]
released v3.1.2, thanks for your feedback~
