### ISSUE TITLE
Flag to indicate if a response was served from cache or not

### ISSUE THREAD

**Issue by adamreisnz** [kuitos/axios-extensions#65]
Can a flag `fromCache` be added to the axios request object to indicate whether the request was served from cache or not?

A similar feature exists in `axios-cache-adapter`, but I prefer to keep using this package.

**Comment by kuitos** [comment]
I am wonder why u need to know if the response from the cache? what scenario?

**Comment by adamreisnz** [comment]
To do some manual checking for cache validation if needed. But I decided to move to `axios-cache-adapter` package instead, because it simply has more features available that are lacking in this package. Rather than try to port them all to this package, I thought it's simpler to just use the other package.
