### ISSUE TITLE
axios-extensions doesn't work with gatsby/webpack due to dependency issue

### ISSUE THREAD

**Issue by magemi** [kuitos/axios-extensions#72]
It appears that this package won't work with with gatsby and/or webpack due to the version of lru-cache (v4.1.5) having a dependency on [pseudomap](https://github.com/isaacs/pseudomap). The pseudomap package sets the `process.env` variables in a way that webpack is unable to handle. 

Is it possible to update this pacakge to use lru-cache v5.x.x as it no longer has a dependency on the pseudomap package?

 [This](https://github.com/gatsbyjs/gatsby/issues/10167#issuecomment-629796378) comment in gatsbyjs/gatsby#10167 helps describe the problem.

**Comment by kuitos** [comment]
pr is welcome

**Comment by shadrech** [comment]
Anyone working on this guys?

**Comment by kuitos** [comment]
fixed and released via v3.1.3
