### ISSUE TITLE
maxAge or throttleAdapterEnhancer

### ISSUE THREAD

**Issue by DragonWhisperer** [kuitos/axios-extensions#79]
Can you make it more clear when to use `maxAge` and when to use `throttleAdapterEnhancer`?

**Comment by kuitos** [comment]
`maxAge` is an option for lru-cache, you can check it out on [lru-cache homepage](https://github.com/isaacs/node-lru-cache#options)

![image](https://user-images.githubusercontent.com/5206843/106240858-f5b9fa80-623f-11eb-84c4-388d993e7ce7.png)
There is an introduction about throttle on our [readme](https://github.com/kuitos/axios-extensions#throttleadapterenhancer)
