### ISSUE TITLE
cacheAdapterEnhancer first parameter must be of type "AxiosAdapter | undefined"

### ISSUE THREAD

**Issue by javi-moralesf** [kuitos/axios-extensions#8]
cacheAdapterEnhancer method expects as first value an adapter of type "AxiosAdapter" but the axios.defaults.adapter type is "AxiosAdapter | undefined". This is causing an error when using TypeSCript

**Comment by kuitos** [comment]
Maybe you need cast the `axios.defaults.adapter` to `AxiosAdapter `
```ts
cacheAdapterEnhancer(axios.defaults.adapter as AxiosAdapter, true)
```

**Comment by kuitos** [comment]
closed
