### ISSUE TITLE
Missing source files for sourcemaps?

### ISSUE THREAD

**Issue by nathanchase** [kuitos/axios-extensions#89]
I'm getting warnings during my dev/build stating that the source maps are missing:
```
 WARN  Sourcemap for "/home/user/myapp/node_modules/.pnpm/axios-extensions@3.1.3/node_modules/axios-extensions/esm/index.js" points to missing source files

 WARN  Sourcemap for "/home/user/myapp/node_modules/.pnpm/axios-extensions@3.1.3/node_modules/axios-extensions/esm/cacheAdapterEnhancer.js" points to missing source files

 WARN  Sourcemap for "/home/user/myapp/node_modules/.pnpm/axios-extensions@3.1.3/node_modules/axios-extensions/esm/utils/buildSortedURL.js" points to missing source files

 WARN  Sourcemap for "/home/user/myapp/node_modules/.pnpm/axios-extensions@3.1.3/node_modules/axios-extensions/esm/utils/isCacheLike.js" points to missing source files

 WARN  Sourcemap for "/home/user/myapp/node_modules/.pnpm/axios-extensions@3.1.3/node_modules/axios-extensions/esm/retryAdapterEnhancer.js" points to missing source files

 WARN  Sourcemap for "/home/user/myapp/node_modules/.pnpm/axios-extensions@3.1.3/node_modules/axios-extensions/esm/throttleAdapterEnhancer.js" points to missing source files
 ```
 Is this something that is misconfigured with the repo?

**Comment by kuitos** [comment]
Checked on [unpkg](https://unpkg.com/browse/axios-extensions@3.1.3/esm/), sourcemap are existed, seems like something wrong with your local environment?
![image](https://user-images.githubusercontent.com/5206843/179922653-a1242d2d-0e6a-45c7-8be1-5518f8291d1f.png)

**Comment by nathanchase** [comment]
Hmm, ok. Maybe it's a byproduct of using pnpm, or the way Vite accesses them. Will look into it. This was the only package in my Nuxt 3 app that was giving me this warning, so I thought I'd mention it. Thanks for checking!

**Comment by jeremiah-snee-openx** [comment]
Npm packages does not include source maps files that the source map files point to. 

<img width="333" alt="Screenshot 2023-07-20 at 11 27 36 AM" src="https://github.com/kuitos/axios-extensions/assets/113928685/bae3e7f7-a55c-4ec5-8ad7-13a73fa4d911">
