### ISSUE TITLE
Missing "./lib/helpers/buildURL" export in "axios" package

### ISSUE THREAD

**Issue by AdilinkOrg** [kuitos/axios-extensions#99]
Hello, I have encountered the following error.

X [ERROR] [plugin vite:dep-pre-bundle] Missing "./lib/helpers/buildURL" export in "axios" package

    node_modules/axios-extensions/esm/utils/buildSortedURL.js:7:21:
      7 │ import buildURL from 'axios/lib/helpers/buildURL';

https://github.com/kuitos/axios-extensions/blob/0b64fd7b155efe0fa65d1025da3ed04d65faef5f/src/utils/buildSortedURL.ts#L8

    "vite": "^4.0.0"
    
    "eslint": "^8.22.0",
    
    "axios": "^1.2.1",
    "axios-cancel": "^0.2.2",
    "axios-extensions": "^3.1.6",

**Comment by boozedog** [comment]
I'm getting same from npm:
```
ERROR in ./node_modules/axios-extensions/esm/utils/buildSortedURL.js 7:0-50
Module not found: Error: Package path ./lib/helpers/buildURL is not exported from package 
```

**Comment by AniaKru95** [comment]
I have the same issue.
I would be appreciate it if appears another solution than downgrading axios version

**Comment by jhvissotto** [comment]
I also have the same issue

**Comment by DmytroVoitovych** [comment]
We’re all waiting for that problem to go away.

**Comment by berkeleymalagon** [comment]
Same issue here :(

**Comment by aoxiang78** [comment]
@AniaKru95 
It should be the reason for the new version of the configuration. Now I temporarily use the alias method, which is feasible.
`     config.resolve.alias.set('axios', join(__dirname, '../node_modules/axios'));`

**Comment by iKnowMagic** [comment]
> @AniaKru95 It should be the reason for axios the new version of the configuration. Now I temporarily use the alias method, which is feasible. ` config.resolve.alias.set('axios', join(__dirname, '../node_modules/axios'));`

I am having the same problem. How would I use the alias method with vue / vite? Thanks.

**Comment by ZhangHanwen96** [comment]
add this ` resolve: {
    alias: {
      // Fix: Missing "./lib/helpers/buildURL" specifier in "axios" package
      // 不知道为啥报错
      'axios/lib': path.resolve(__dirname, './node_modules/axios/lib')
    }
  }` in vite config

**Comment by boozedog** [comment]
> Axios 1.x has a little breaking changes in its package.json, you could downgrade axios to 0.x as a workaround, I will look into it later and try to solve it really.

@kuitos any luck? Just tried 1.x.x today and still broken

**Comment by mengqiuleo** [comment]
about `./lib/`，perhaps can refer to https://github.com/axios/axios/issues/5072 and https://github.com/axios/axios/pull/5136, the result is https://github.com/axios/axios/pull/5136#issuecomment-1289042917.

**Comment by crhistianramirez** [comment]
> add this ` resolve: { alias: { // Fix: Missing "./lib/helpers/buildURL" specifier in "axios" package 'axios/lib': path.resolve(__dirname, './node_modules/axios/lib') } }` in vite config

Nice, thanks! I was able to use a similar config in next.js by updating next.config.jx

```typescript
webpack: (config) => {
    config.resolve.alias = {
        ...config.resolve.alias,
            // Fix: Missing "./lib/helpers" specifier in "axios" package 
            'axios/lib': path.resolve(__dirname, './node_modules/axios/lib'),
    }

    return config;
}
```

**Comment by Dhana-tech-code** [comment]
i'm also facing this issue -

node_modules/axios-extensions/esm/utils/buildSortedURL.js:7:21:
  7 │ import buildURL from 'axios/lib/helpers/buildURL';
  
  if i downgrade to lower version of axios 0.x, the ordercloud-sdk is getting break since its expecting 1.1.3 
  
  can anyone help on this

**Comment by Dhana-tech-code** [comment]
@crhistianramirez - i'm using nextJS only but still facing issue like target is undefined , can i get whole code of your next.config.js file
